package com.sx.rbac.entity;

import java.io.Serializable;

import com.sx.core.entity.PageEntity;

@SuppressWarnings("serial")
public class DepartmentEntity implements Serializable{
	private String id;
	private String parentPath;
	/**
	 * 父类节点编号
	 **/
	private Integer parentNodeId;
	/**
	 *样式 
	 **/
	private String iconCls = "depicon";
	/**
	 *是否为叶子节点 
	 **/
	public Boolean leaf ;
	/**
	 *是否为选中节点
	 * 
	 **/
	public Boolean checked ;
	/**
	 *孩子的数量 如果为0叶子节点 如果大约0说明不是叶子节点 
	 ***/
	private Integer childcount;
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPID
     * 部门编号
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private Integer depid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPNUM
     * 部门自定义代码
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depnum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPNAME
     * 部门名称
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPCN
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depcn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPPHONE
     * 部门电话
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depphone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPPARENTID
     * 部门父级单位代码
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private Integer depparentid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPPARENTNAME
     * 部门父级单位名称
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depparentname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPEMAIL
     * 部门邮件
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depemail;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPFAX
     * 部门传真
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depfax;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPFUNCTION
     * 部门职能
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depfunction;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPSTATUS
     * 部门状态
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depstatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPTYPE
     * 部门类别
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String deptype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPLVL
     * 部门级别
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String deplvl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPPRSN
     * 部门负责人名称
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depprsn;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPPRSNID
     * 部门负责人编号
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private Integer depprsnid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPROLES
     * 部门权限
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String deproles;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPADDRESS
     * 部门地址
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depaddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.DEPZIPCODE
     * 部门邮编
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String depzipcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.deplevel
     * 与上级的关联关系
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    private String deplevel;
    
    public String getParentPath() {
		return parentPath;
	}

	public void setParentPath(String parentPath) {
		this.parentPath = parentPath;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column sys_zbdep001.childcount
     * 下级单位的个数
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
   
    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the iconCls
	 */
	public String getIconCls() {
		iconCls = "depicon";
		return iconCls;
	}

	/**
	 * @param iconCls the iconCls to set
	 */
	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPID
     *
     * @return the value of sys_zbdep001.DEPID
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public Integer getDepid() {
        return depid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPID
     *
     * @param depid the value for sys_zbdep001.DEPID
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepid(Integer depid) {
        this.depid = depid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPNUM
     *
     * @return the value of sys_zbdep001.DEPNUM
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepnum() {
        return depnum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPNUM
     *
     * @param depnum the value for sys_zbdep001.DEPNUM
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepnum(String depnum) {
        this.depnum = depnum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPNAME
     *
     * @return the value of sys_zbdep001.DEPNAME
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPNAME
     *
     * @param depname the value for sys_zbdep001.DEPNAME
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepname(String depname) {
        this.depname = depname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPCN
     *
     * @return the value of sys_zbdep001.DEPCN
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepcn() {
        return depcn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPCN
     *
     * @param depcn the value for sys_zbdep001.DEPCN
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepcn(String depcn) {
        this.depcn = depcn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPPHONE
     *
     * @return the value of sys_zbdep001.DEPPHONE
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepphone() {
        return depphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPPHONE
     *
     * @param depphone the value for sys_zbdep001.DEPPHONE
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepphone(String depphone) {
        this.depphone = depphone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPPARENTID
     *
     * @return the value of sys_zbdep001.DEPPARENTID
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public Integer getDepparentid() {
        return depparentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPPARENTID
     *
     * @param depparentid the value for sys_zbdep001.DEPPARENTID
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepparentid(Integer depparentid) {
        this.depparentid = depparentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPPARENTNAME
     *
     * @return the value of sys_zbdep001.DEPPARENTNAME
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepparentname() {
        return depparentname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPPARENTNAME
     *
     * @param depparentname the value for sys_zbdep001.DEPPARENTNAME
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepparentname(String depparentname) {
        this.depparentname = depparentname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPEMAIL
     *
     * @return the value of sys_zbdep001.DEPEMAIL
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepemail() {
        return depemail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPEMAIL
     *
     * @param depemail the value for sys_zbdep001.DEPEMAIL
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepemail(String depemail) {
        this.depemail = depemail;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPFAX
     *
     * @return the value of sys_zbdep001.DEPFAX
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepfax() {
        return depfax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPFAX
     *
     * @param depfax the value for sys_zbdep001.DEPFAX
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepfax(String depfax) {
        this.depfax = depfax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPFUNCTION
     *
     * @return the value of sys_zbdep001.DEPFUNCTION
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepfunction() {
        return depfunction;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPFUNCTION
     *
     * @param depfunction the value for sys_zbdep001.DEPFUNCTION
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepfunction(String depfunction) {
        this.depfunction = depfunction;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPSTATUS
     *
     * @return the value of sys_zbdep001.DEPSTATUS
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepstatus() {
        return depstatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPSTATUS
     *
     * @param depstatus the value for sys_zbdep001.DEPSTATUS
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepstatus(String depstatus) {
        this.depstatus = depstatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPTYPE
     *
     * @return the value of sys_zbdep001.DEPTYPE
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDeptype() {
        return deptype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPTYPE
     *
     * @param deptype the value for sys_zbdep001.DEPTYPE
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDeptype(String deptype) {
        this.deptype = deptype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPLVL
     *
     * @return the value of sys_zbdep001.DEPLVL
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDeplvl() {
        return deplvl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPLVL
     *
     * @param deplvl the value for sys_zbdep001.DEPLVL
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDeplvl(String deplvl) {
        this.deplvl = deplvl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPPRSN
     *
     * @return the value of sys_zbdep001.DEPPRSN
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepprsn() {
        return depprsn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPPRSN
     *
     * @param depprsn the value for sys_zbdep001.DEPPRSN
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepprsn(String depprsn) {
        this.depprsn = depprsn;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPPRSNID
     *
     * @return the value of sys_zbdep001.DEPPRSNID
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public Integer getDepprsnid() {
        return depprsnid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPPRSNID
     *
     * @param depprsnid the value for sys_zbdep001.DEPPRSNID
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepprsnid(Integer depprsnid) {
        this.depprsnid = depprsnid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPROLES
     *
     * @return the value of sys_zbdep001.DEPROLES
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDeproles() {
        return deproles;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPROLES
     *
     * @param deproles the value for sys_zbdep001.DEPROLES
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDeproles(String deproles) {
        this.deproles = deproles;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPADDRESS
     *
     * @return the value of sys_zbdep001.DEPADDRESS
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepaddress() {
        return depaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPADDRESS
     *
     * @param depaddress the value for sys_zbdep001.DEPADDRESS
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepaddress(String depaddress) {
        this.depaddress = depaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.DEPZIPCODE
     *
     * @return the value of sys_zbdep001.DEPZIPCODE
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDepzipcode() {
        return depzipcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.DEPZIPCODE
     *
     * @param depzipcode the value for sys_zbdep001.DEPZIPCODE
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDepzipcode(String depzipcode) {
        this.depzipcode = depzipcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column sys_zbdep001.deplevel
     *
     * @return the value of sys_zbdep001.deplevel
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public String getDeplevel() {
        return deplevel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column sys_zbdep001.deplevel
     *
     * @param deplevel the value for sys_zbdep001.deplevel
     *
     * @abatorgenerated Wed Apr 13 10:12:28 CST 2011
     */
    public void setDeplevel(String deplevel) {
        this.deplevel = deplevel;
    }

	/**
	 * @return the childcount
	 */
	public Integer getChildcount() {
		return childcount;
	}

	/**
	 * @param childcount the childcount to set
	 */
	public void setChildcount(Integer childcount) {
		this.childcount = childcount;
	}

	/**
	 * @return the leaf
	 */
	public Boolean isLeaf() {
		if(getChildcount()!=null&&getChildcount().intValue()==0)
		{
			leaf = true;
		}
		return leaf;
	}

	/**
	 * @param leaf the leaf to set
	 */
	public void setLeaf(Boolean leaf) {
		this.leaf = leaf;
	}

	/**
	 * @return the checked
	 */
	public Boolean isChecked() {
		return checked;
	}

	/**
	 * @param checked the checked to set
	 */
	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	public Integer getParentNodeId() {
		return parentNodeId;
	}

	public void setParentNodeId(Integer parentNodeId) {
		this.parentNodeId = parentNodeId;
	}
}
